module-11/demo/demo/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('todos/', include('porg.urls')),
    path('admin/', admin.site.urls),
    path('', views.index)
]

module-11/demo/porg/urls.py
'''
Jess Monnier, CSD-325 Assignment 11.2, 9 March 2025
The urls defined in this script came from the following GitHub distro:
https://github.com/shreys7/django-todo/tree/develop
'''

from django.urls import path
from . import views

app_name='todos'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:todo_id>/delete', views.delete, name='delete'),
    path('<int:todo_id>/update', views.update, name='update'),
    path('add/', views.add, name='add'),
    path('about.html', views.about, name='about') # I added this one
]

module-11/demo/porg/models.py
from django.db import models

class Todo(models.Model):
    title = models.CharField(max_length=100)
    created_at = models.DateTimeField('Created', auto_now_add=True)
    update_at = models.DateTimeField('Updated', auto_now=True)
    isCompleted = models.BooleanField(default=False)

    def __str__(self):
        return self.title

module-11/demo/porg/forms.py
from django.forms import ModelForm
from django import forms
from .models import Task, Category

# Makes a more user friendly way of selecting a date/time for a task
class DateTimePickerInput(forms.DateTimeInput):
    input_type = 'datetime-local'

# Make the input form used to display & edit/submit tasks
# The attrs class form-control thing is for CSS styling
class FormTask(ModelForm):
    class Meta:
        model = Task
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
            'due_date': DateTimePickerInput(attrs={'class': 'form-control'})
        }

# Make the input form used to display and edit/submit task categories
class FormCategory(ModelForm):
    class Meta:
        model = Category
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'})
        }

module-11/demo/demo/views.py
from django.shortcuts import redirect

def index(request):
    return redirect('/todos')

module-11/demo/porg/views.py
'''
Jess Monnier, CSD-325 Assignment 11.2, 9 March 2025
The views defined in this script came from the following GitHub distro:
https://github.com/shreys7/django-todo/tree/develop
I've added my own comments partly to increase my understanding of them.
'''

from django.shortcuts import get_object_or_404, redirect, render
from django.views import generic
from .models import Todo

# This allows for the todo items to be pulled into
# the index in reverse creation order
class IndexView(generic.ListView):
    template_name = 'index.html'
    context_object_name = 'todo_list'

    def get_queryset(self):
        """Return all the latest todos."""
        return Todo.objects.order_by('-created_at')

# Allows a new todo item to be added and the page refreshed
def add(request):
    title = request.POST['title']
    Todo.objects.create(title=title)

    return redirect('todos:index')

# Allows an existing todo to be deleted and the page refreshed
def delete(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    todo.delete()

    return redirect('todos:index')

# Allows an existing todo to be toggled between complete/incomplete
def update(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    isCompleted = request.POST.get('isCompleted', False)
    if isCompleted == 'on':
        isCompleted = True
    
    todo.isCompleted = isCompleted

    todo.save()
    return redirect('todos:index')

# This one I added. It just shows the contents of about.html.
def about(request):
    return render(request, "about.html")

module-11/demo/porg/templates/about.html
<!-- 
	Jess Monnier, CSD-325 Assignment 11.2, 9 March 2025
	I based this page heavily on the todo page code in index.html
    but added my own content within the content div.
-->

{% extends "base.html" %} {% block title %} About {% endblock %}
{% block content %}
<div class="container">

    <!-- title row -->
    <div class="row">
      <div class="offset-md-2 col-lg-9">
        <div class="page-header">
          <h1>
            About This Site
          </h1>
        </div>
      </div>
    </div>
    <hr />
  
    <!-- content -->
    <div class="row">
      <div class="offset-md-2 col-lg-6">
        <div class="list-group">
          <div class="list-group-item">
            <p>This is an experimental Django site for me (Jess Monnier) to play around with Python in the context of a website. 
            I used <a href="https://www.youtube.com/watch?v=nGIg40xs9e4">this YouTube video</a> ("Learn Django in 20 Minutes!" 
            by Tech with Tim) and <a href="https://github.com/shreys7/django-todo/tree/develop">this GitHub distro</a> 
            ("django-todo" by shreys7) as the basis for the Todo App on this site, but I made some tweaks:</p>
            <ul>
                <li>
                    Since the base.html template in the video tutorial uses Bootstrap 4, which doesn't support glyphicons, I had 
                    to switch the trashcan icon to SVG in a span that uses an adjusted version of the original icon's CSS styling.
                </li>
                <li>
                    I used the default static folder model for Django rather than the adjusted one the GitHub distro was using.
                </li>
                <li>
                    I added this page and updated the links in base.html to be functional.
                </li>
            </ul>
            <p>No major changes, just little things I had to figure out to get the two slightly different templates to work together 
            properly. I went through a couple different todo app templates before finding one that was the right fit for my current 
            level of understanding about Django. I'm excited to grow my expertise in this area!</p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

module-11/demo/porg/templates/base.html
<!-- 
	Jess Monnier, CSD-325 Assignment 11.2, 9 March 2025
	I copied the bulk of this template from the video tutorial.
	(Yeah, I paused it and copied it, I'm just extra I guess.)
	I added a static link to the todo stylesheet and made the Home
	and About links functional. And that's about it!
-->
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta
			name="viewport"
			content="width=device-width, initial-scale=1, shrink-to-fit=no"
		/>
		<title>{% block title %}Django App{% endblock %}</title>
		<!-- Bootstrap CSS -->
		<link
			href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
			rel="stylesheet"
		/>
		<link rel="stylesheet" href="{% static 'todo_style.css' %}">
	</head>
	<body class="container-fluid">
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<a class="navbar-brand" href="#">My Django App</a>
			<button
				class="navbar-toggler"
				type="button"
				data-toggle="collapse"
				data-target="#navbarNav"
				aria-expanded="false"
				aria-label="Toggle navigation"
			>
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav">
					<li class="nav-item">
						<a class="nav-link" href="/">Home</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="about.html">About</a>
					</li>
				</ul>
			</div>
		</nav>
		
		<div class="container">{% block content %} {% endblock %}</div>
		
		<!-- jQuery and Bootstrap Bundle (includes Popper) -->
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
	</body>
</html>

module-11/demo/porg/templates/index.html
<!-- 
	Jess Monnier, CSD-325 Assignment 11.2, 9 March 2025
	I copied the bulk of this template from the github distro below:
    https://github.com/shreys7/django-todo/tree/develop
    I updated the delete icon on the todo items to work with 
    Bootstrap 4, but that's pretty much it.
-->

{% extends "base.html" %} {% block title %} Todo List {% endblock %}
{% block content %}
<div class="container">

    <!-- title row -->
    <div class="row">
      <div class="offset-md-2 col-lg-9">
        <div class="page-header">
          <h1>
            Todo List
          </h1>
        </div>
      </div>
    </div>
  
    <!-- Add a todo row -->
    <div class="row">
      <div class="offset-md-2 col-lg-9">
        <form method="post" action="{% url 'todos:add' %}">
          {% csrf_token %}
          <div class="form-row">
            <div class="col-md-6">
              <input type="text" class="form-control" name="title" placeholder="Do laundry" required>
            </div>
            <div class="col-md-6">
              <button type="submit" name="submit" class="btn btn-outline-primary">
                Add
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
    <hr />
  
    <!-- todo list row -->
    <div class="row">
      <div class="offset-md-2 col-lg-6">
        <div class="list-group">
          {% for todo in todo_list %}
          <div class="list-group-item {% if todo.isCompleted %} todo-complete {% endif %}">
            <form style="display: inline;" method="post" action="{% url 'todos:update' todo.id %}">
              {% csrf_token %}
              <input type="checkbox" name="isCompleted" onchange="this.form.submit()" {% if todo.isCompleted %} checked
                {% endif %} class="todo-status-checkbox"
                title="{% if not todo.isCompleted %} mark as done {% else %} mark undone {% endif %}">
            </form>
            {{ todo.title }}
            <span style="display:block;float:right">
            <a href="{% url 'todos:delete' todo.id %}" title="Delete" class="fa-trash-alt">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                    <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5"/>
                  </svg>
            </a>
            </span>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}